spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      dialect:
        hibernate: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
app:
  jwtSecret: ${jwt_secret}
  jwtExpiration: 604800000