version: '3'

services:
  auctionapp-db:
    image: tmarkesic/auction-db
    environment:
      POSTGRES_DB: auctionapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auction
    
  auctionapp-be:
    image: tmarkesic/auction-be
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://auctionapp-db:5432/auctionapp?useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: auction
      aws_access_key: AKIA4KCKUJQPBPW3EJPE
      aws_secret_key: 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
      APP_JWTSECRET: d178899b7beeb99ec2ebdad4636c7e21a2364494414013f78dd5a00725b77f14
    ports:
      - "8080:8080"
    depends_on:
      - auctionapp-db
  
  auctionapp-fe:
    image: tmarkesic/auction-fe
    ports:
      - "3000:80"
    depends_on:
      - auctionapp-be

networks:
  auctionapp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
